# MQTT Configuration for OpenIPC Doorphone
MQTT_ENABLED="true"
MQTT_HOST="192.168.1.30"
MQTT_PORT="1883"
MQTT_USER="user"
MQTT_PASS="passwd"
MQTT_CLIENT_ID="$MQTT_CLIENT_ID"
MQTT_TOPIC_PREFIX="doorphone"
MQTT_DISCOVERY="true"
MQTT_DISCOVERY_PREFIX="$MQTT_DISCOVERY_PREFIX"
